raise ValueError('A very specific bad thing happened')
